Install iOS 17 runtime on MacOS 26 for nightly runs.

diff --git a/.github/workflows/reusable-workflow.yaml b/.github/workflows/reusable-workflow.yaml
--- a/.github/workflows/reusable-workflow.yaml
+++ b/.github/workflows/reusable-workflow.yaml
@@ -41,6 +41,9 @@ jobs:
         run: |
           ./install.sh
           echo $TEST_CREDENTIALS > ./shared/test/test_credentials.json
+      - name: Install iOS 17 runtime if needed
+        if: ${{ inputs.ios == '^17' }}
+        run: xcodes runtimes install "iOS 17.5"
       - uses: mxcl/xcodebuild@v3
         with:
           xcode: ${{ inputs.xcode }}
@@ -58,7 +61,8 @@ jobs:
           show-code-coverage: false
           upload-bundles: false
           show-passed-tests: false
-        if: ${{ ! inputs.build_only && (success() || failure()) }}
+        # xcresulttool currently fails for iOS 26
+        if: ${{ ! inputs.build_only && (success() || failure()) && inputs.ios != '^26' }}
       - uses: codecov/codecov-action@v4
         with:
           flags: ${{ inputs.lib }}
